# Generated by Django 5.2.8 on 2025-11-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('phone_number', models.TextField(blank=True, max_length=15)),
                ('role', models.CharField(choices=[('client', 'Client'), ('seller', 'Seller'), ('courier', 'Courier'), ('admin', 'Admin')], default='client', max_length=10)),
                ('address', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
